### ISSUE TITLE
Your gut reaction to the prototype

### ISSUE THREAD

**Issue by kytrinyx** [exercism/v2-feedback#1]
This is the place to put all those messy... you know... feelings. 💖 

If you have thoughts that are kind of amorphous, things that aren't really quite thought out or thought through, impressions, wishes, musings, anything that doesn't quite fit into a nice box and a tidy topic, this is the place for it.

**Comment by rpottsoh** [comment]
>Thanks for stopping by and helping make Exercism awesome. If you've not done already, please read this document which explains how and why this new version of Exercism has happened, and how you can help us make it amazing.

I think `so` should be inserted between `done` and `already`.  I have not gone any further, I wanted to point this out while it was still in front of me.

**Comment by tleen** [comment]
On a gut (immediate reaction) level it is impressive visually. Time to dig in though.

**Comment by rpottsoh** [comment]
WOW!  :+1:  :1st_place_medal:

**Comment by tleen** [comment]
The [Go Gopher](https://blog.golang.org/gopher) is [tracking](https://v2.exercism.io/#explore-languages). I love it.

**Comment by rpottsoh** [comment]
Under account settings, I changed my Privacy settings from the default state.  After I clicked `Update My Privacy Settings` the selection I had changed (Delphi Pascal Track) reverted to its original state.  I was informed that the track settings were updated successfully.

**Comment by kytrinyx** [comment]
@rpottsoh would you mind opening an issue with this (screenshots of the different steps would be super helpful)?

**Comment by tejasbubane** [comment]
All the icons looks amaziiing 😻

**Comment by NobbZ** [comment]
First impression:

* Miss the small devil ;(
* Some places where I do have problems to read either due to low contrast or small fonts or even both.
* I can't get used to this “mint” theme…
* Cute exercise icons are lost after they are solved (replaced by checkmark)

**Comment by ilya-khadykin** [comment]
agree with @NobbZ, I liked the previous site logo (it's a big shift). 
The font size seems a bit small and hard to read on high resolution displays, here for example - https://v2.exercism.io/my/tracks/cpp

Other than this small issues, it looks awesome! Plus there are a lot of new features. Loved the track dashboard with useful insights on the progress

**Comment by NobbZ** [comment]
After digging a bit deeper…

* The "prepared tour" only tells you how to install nextercism and how to download the exercise, it does not explain what do now, so that you are ready to solve right now and how you have to submit after that, you have to guess.
* I'm a mentor on every track I am a student on…
* There are `hello-worlds` from the go-track waiting for a review… Can I safely take a look or is that a claim on the submission and it will be unavailable for other mentors? I'm missing a mentors handbook…

**Comment by ilya-khadykin** [comment]
@NobbZ 
> I'm a mentor on every track I am a student on…

It's Ok, it's done on purpose for testing

**Comment by NobbZ** [comment]
> It's Ok, it's done on purpose for testing

Thats been my assumption, but a word of warning had been nice ;)

**Comment by ilya-khadykin** [comment]
@NobbZ 
From https://github.com/exercism/v2-feedback/blob/master/README.md:
>During the beta testing period we are automatically opting all beta testers into being a mentor when they first create their account in the prototype. In the final phase of beta testing we will turn this off so that we can test the actual user experience of not being a mentor, the calls to action to become one, and signing up.

**Comment by NobbZ** [comment]
No one ever reads past a TLDR ;)

**Comment by Insti** [comment]
Site looks pretty.
I like the new logo/theme, language icons, problem icons.
Still a lot of workflow rough edges.
VERY STRONGLY DISLIKE that you need mentor "approval" to move to the next problem.

**Comment by kytrinyx** [comment]
@NobbZ Please read past the TL;DR.

@Insti I hear you about requiring mentor approval. We're still discussing trade-offs, usability, and user experience in this area.

**Comment by NobbZ** [comment]
> Please read past the TL;DR.

I usually do, but only skimming. Perhaps I missed that part. The smilie in my post was meant to tell that I've read further but maybe missed something.

**Comment by kytrinyx** [comment]
Ah, OK. It's really hard to know, as you're right: many people do not read past the TL;DR.

I know there's a ton of information there, and I do think it's all relevant (I tried very hard to skip past the things that are not necessarily crucial for people to know up front).

**Comment by lpatmo** [comment]
It looks BEAUTIFUL; we've had a weekly study group at CodeBuddies for several months now working through exercism exercises in the python track, and @bethanyg has sufficiently convinced us on Slack that we should all help out since we've benefited so much from discussing the exercises. :)

Occurred to me that it might be helpful to have a link to `Issues` in the "Where to submit feedback", section, so readers not as familiar with Github know immediately where to file feedback. And might be helpful to mention that when you log in to v2, you immediately have access to a Mentors dashboard. I was clicking the "Sign up as a mentor" link in the footer, and it wasn't immediately clear to me that I didn't have to sign up as a mentor in beta in order to test out that feature.

**Comment by Insti** [comment]
> @Insti I hear you about requiring mentor approval. We're still discussing trade-offs, usability, and user experience in this area.

Should there be an issue here to discuss this?

I'm trying to use Nextercism to learn a new language, but my enthusiastic progress has hit a brick wall because I cannot continue to the next problem.

**Comment by NobbZ** [comment]
> * I can't get used to this “mint” theme…

I'm just realising that this “mint” theme is only on a tracks progress page, while on all other pages the theme seems to be much more of a blue.

Track page has:

```css
#my-track-page .header {
    background-color: #3ab292;
}
```

While track-list has:

```css
#my-tracks-page .header {
    background-color: #009cab;
}
```

Other colors on that corresponding pages are matching header-background.

Personally I like that blue-ish theme more than the mint-ish one. Also it seems to be more consistent with the theme that is used on the pages which are reachable via the links in the footer. The "track-progress" page is actually the only one I was able to find using the mint theme.

**Comment by Insti** [comment]
I'm not sure if this is worthy of it's own issue, or just something that I'm the only one who cares about it.

There are too many pages that are not visible if you are logged in or subscribed (or not) to a track. eg:
https://v2.exercism.io/
https://v2.exercism.io/tracks/ruby
(I'm sure there are more.)

I prefer URLs that are URLs and don't change content completely just because one is logged in.

**Comment by NobbZ** [comment]
@insti I think that's covered by #15.

**Comment by Insti** [comment]
Yes #15 applies here. Thanks @NobbZ

**Comment by rpottsoh** [comment]
I'm also missing the old logo.  The old logo really stood out in a crowd.

**Comment by iHiD** [comment]
### Mentorship.

@Insti Please feel free to open an issue and I will explain in more depth why we've made this change.

### Logo

The Readme has some great explanation on why we have changed the logo. Being welcoming and inclusive matters more to us than anything else, and the old logo didn't achieve that. The new one does.

### Colors

We're really pleased with the colours and designs we've chosen. We're happy to look into specific issues with contrast so please open an issue if there is a place where that is the case. 

> I can't get used to this “mint” theme…

I doubt 6hrs is enough time for one's brain to adapt to a change of a UI that one has used for a long time. You'll get used to it :)

**Comment by kytrinyx** [comment]
> Occurred to me that it might be helpful to have a link to Issues in the "Where to submit feedback", section

@lpatmo Good point, adding that. ❤️

**Comment by NobbZ** [comment]
> ## Logo
>
> The Readme has some great explanation on why we have changed the logo. Being welcoming and inclusive matters more to us than anything else, and the old logo didn't achieve that. The new one does.

Yes, I read the reasoning behind changing the logo, I do even share some of the thoughts, still after beeing a user of v1 for many years, I've built some kind of bond to our small devel (typo intended) ;). I think the very same applies to the other voices that miss it. We were asked about out gut feelings, so we feel free to share. Also we feel free to disagree with decissions that were made. And as you can see, even while agreeing with the reasong behind a change, we might disagree with the change itself, just because we started to love the status-quo.

---

>> I can't get used to this “mint” theme…
>
> I doubt 6hrs is enough time for one's brain to adapt to a change of a UI that one has used for a long time. You'll get used to it :)

Maybe, also I can create a user-stylesheet if I feel to do so, but still I think theming/branding should be applied consistently.

**Comment by ErikSchierboom** [comment]
In general: I love it. It looks crisp and clean and has tons of filtering functionality that I always wanted. A lot of rough edges, but that is to be expected. The quality is apparent and has got me really excited for the finished product.

> VERY STRONGLY DISLIKE that you need mentor "approval" to move to the next problem.

I have to agree. Although I think the mentorship idea is great, I do think people should be able to move to the next exercise without being blocked. Occasionally, I really immerse myself in a language and then I just churn out several consecutive exercises. This blocking approach would make that far less feasible.

As for the logo: I don't mind the new logo as I also wasn't really attached to the previous one. But I have to admit that the "smiley" bit looks a bit odd to me and is the font of the logo different from the website? It seems to be much more curvy, which fits less with the rest of the website I feel.

**Comment by BethanyG** [comment]
Humm.  Quick gut feelings.  I will miss the old logo (I loved the pun) and color.  But I fully support and understand the re-design.  I agree with @ErikSchierboom - the "smiley" is a bit jarring to me.  

Otherwise, the site feels fresh, modern, and very very welcoming.  It's pretty darn awesome.  I absolutely love that the coders change with every refresh - and the new language logos are really nice. I also really like the font choices - but I agree with (and I can't find the user) whoever mentioned that the font may be a tad small on hi-res screens. And at least on my iPhone, the color is displaying *just light enough* that it's causing me to squint a bit.  Not sure why - on my desktop, the font color is perfect.  And I know it's a prototype..but it's not adjusting to either the iPhone or iPad screen size (guess this is #34 ...)

I also really like that I can clearly see which language tracks I've joined, and which ones are available.  All the work around language tracks and progress is really cool.  

It's less clear to me (probably because I am being added as a mentor by default) which tracks I am mentoring for - and which ones I'm not without leaving a track.  Is that being signified by the color change from blue to mint?  I couldn't track/see any other indicator of my mentor (as opposed to learner) role outside of my profile or the drop-down. 

It might also be nice (for the polyglots out there) to have the mentor dashboard grouped by language - or have the individual language icons there be higher contrast or bigger (related to #14 I guess).  It would be great if I could see at a glance what review help was needed where, and if I needed to concentrate on say, a backlog in Python or JS or something.

Also wondering out loud here about how learners become mentors and _when_ they're prompted to become mentors.  I've found that in the groups I have been a part of, new learners get a LOT out of turning around and helping others with topics they themselves have already mastered.  And I have gotten a tremendous amount out of helping with easier problems whilst learning to tackle more complex ones.  So I am not sure what that looks like within the current design.

**Comment by rpottsoh** [comment]
The googly GOpher eyes are creeping me out.  👀   [being sarcastic]  Just noticed his eyes following me around this morning on the available tracks section of the landing page.  👍

**Comment by medwards1771** [comment]
Initial reactions with respect to design:

Looks nice. Very user friendly. Really, truly appreciate the hard work that went into this and that will continue to go in nextercism. 

I like the new logo and the the reasoning behind it. 

What I miss: This new design makes the site feel like every other learn-to-code platform out there. I miss that old edge, the feeling that exercism was special and different. This design (especially the color scheme) doesn't do justice to the weirdness of our community -- we're warm and friendly and believe strongly in mentorship YES, but we're also wacky and funny and unusual. This new exercism doesn't quite evoke the vibe that exercism is a safe haven from the mainstream, often combative coding space.

**Comment by iHiD** [comment]
@medwards1771 Thanks for your comments :) 

> is a safe haven from the mainstream, often combative coding space.

Is there anything specifically that you can identify that made the old site feel safer or less combative than what is here now?

**Comment by medwards1771** [comment]
@iHiD Thanks so much for reading my comment and taking the time to respond!

Great question. I will do my best to answer. The familiarity of the design, my initial impression that it looks generic, and its "looks like every other learn-to-code site out there" feel all contribute to the new site not feeling like as much of a safe haven. Also, I really do not like that students seem to need mentor approval to advance or even that students need to complete a core set of exercises in each track to unlock others. I like the unstructured old version because it placed *trust* in users to work at their own pace and progress however they saw fit for themselves.

There is nothing combative about the new site design. It's more it's that I'm looking for something a little unpolished or weird or different in the design :)

**Comment by kytrinyx** [comment]
Thank you @medwards1771 💙 

> I like the unstructured old version because it placed trust in users to work at their own pace and progress however they saw fit for themselves.

I found this bit really interesting. Would you mind posting it to https://github.com/exercism/v2-feedback/issues/36?

**Comment by robphoenix** [comment]
I love the new site, looks *totes profesh*! It's welcoming, encouraging, and fun. While I can agree with some comments that it loses an edginess, I'd almost have to counter that that increases it's potential as a safe space by losing what could be considered a shibboleth.
I dig the new logo and love the `exercism` logo font, what is that?
It really feels like a graduation, a maturation.

**Comment by antonpaisov** [comment]
Congratulations on the beta launch!!!
Gopher eyes <3
Font (family, size, contrast ratio to background) combo feels as not the most readable in some places, reminded me of this article https://www.wired.com/2016/10/how-the-web-became-unreadable/

Will start testing more extensively tomorrow.

I also miss devil logo and red color :)

**Comment by iHiD** [comment]
Thanks @antonpaisov :) What browser/os combo are you using?

**Comment by antonpaisov** [comment]
@iHiD Thinkpad t460 (14' FHD screen) Ubuntu Gnome 17.04 + Chrome.
I've also tried it on the MacBook Air 13 + Chrome just now and I have almost the same feeling, with MBA resolution at 1440x900 the font looks blurry and pixelated.
Setting paragraph font-weight to `normal` help, or if you want to keep the font-weight `light`, I would increase the font-size from 16 to 20.

Screenshots:
how it looks on the Thinkpad: https://drive.google.com/file/d/0Bw_pIMQo_j8GOS1aV09HcDFiWDA/view?usp=sharing
how it looks when weight set to `normal`: https://drive.google.com/file/d/0Bw_pIMQo_j8GX2c5cmRWa3ZCSTg/view?usp=sharing

here's how tracks page look: https://drive.google.com/file/d/0Bw_pIMQo_j8GbkFYdFUxck8wbWM/view?usp=sharing almost all fonts are unreadable to me :( 

One last thing. I think the accessibility of exercism is a very important thing.
Example: my mom is currently trying to learn Go, but because of decreased eyesight it would be even harder for her to use v2 in with current font weights.

Cheers :)

**Comment by duckmole** [comment]
I discover that some track have Concepts tag : it's so cool. I will not have to create anymore it, as I done.

**Comment by antonpaisov** [comment]
follow up to my comment: I believe the readability issue is visible only on non-hidpi screens (mac+linux confirmed, but especially linux)

**Comment by wolf99** [comment]
First impressions on the visual design: I like it! The overall lighter colour seems more open and the design itself seems more "a product" , or professional I guess.

A few small things: 

First, while it's been kept over from the old design, the dark bar at the top of the pages feels... top-heavy, maybe something lighter (though still with contrast to the main page area)? 

Second, the available language listings on the front page seem to re-arrange themselves randomly on reload. not sure if this is by design but it makes it harder than it should be to find the same language on subsequent visits. maybe they could be sorted alphabetically?

Third, if not signed in and I visit a language, eg C++, click to view all the exercises and then click one of them, say the hello world (https://v2.exercism.io/tracks/cpp/exercises/hello-world) - the result is an "Oh dear, something's not working here...".  Unsure if this is covered by #2 or not.

Fourth, I cant see upcoming or planned tracks. Maybe this is in the TODO work or something. I got started with Exercism on the C track, which still hasn't graduated from upcoming. If I came to the site wanting to do some C exercises and saw it wasn't listed I would leave again without even signing up, without knowing that there *is* in fact a C track, that is usable and that I could contribute to. This would probably end up with such tracks dying off or never coming to be in the first place because people would never see them and never contribute to them.

Fifth, in the logged in user menu (clicking on my profile icon at top right), what is the supposed difference between "Settings" and "Preferences"? To me they pretty much mean the same thing with regards to a website. Communications preferences vs communications settings seems a pretty small distinction, the button on the preferences page even says "Save *settings*". Perhaps this is intended to accommodate potential growth in each of these categories? If so I would still recommend consolidating to one menu, the resulting page then having several sub-pages - see GitHub Settings for a great example!

Finally, on pages that aren't long enough to fill the browser window, the footer lifts up away from the bottom leaving a pile of white-space underneath, instead of extending the white-space above as is normally the expected style for webpages in general. An example is the account preferences page.

Sorry that "my 2c" turned out much longer than I thought!

**Comment by kytrinyx** [comment]
@wolf99 Thanks for this!

For (2) this is, indeed, intentional: https://github.com/exercism/v2-feedback/issues/3

For the other points, would you open individual discussions for them so that we can react individually and track them?

**Comment by remcopeereboom** [comment]
I'm not sure if you are still looking for feedback, but the issue is still open... I just found out you were creating a new site. Love the design. It definitely feels a lot friendlier (especially the logo, of which I was always concerned that it might be off-putting to some).

I checked out the "learners" side and it seems well thought out. There is a lot of hand holding, but not in obnoxious way. I noticed that the banner has the numbers formatted inconsistently (can't help old style nitpicking): 10,816 Students | 10816 Mentors

I would love to give some feedback on the mentoring, but almost none of the buttons seem to be working and all the scroll-bars are doubled, so I'm guessing the mentor page is still on the TODO list.  

Despite all the love for the new design (seriously you guys are doing **amazing** work), there are a few negatives for me:

1. The top-banner is very big. This may look nice, but it means that I have to scroll down every time I load the page. As someone who logs in and out many times a day to review submissions, that's a huge time waster and was something that I already found cumbersome in the old design.
2. The comments are posted below the submission even on large screen sizes. This means that a) I need to find them first; b) scroll down to read them; and c) I need to scroll up to see the code the comments refer to.
3. I have no idea what to do with the "good job", "love it", "genius" buttons. When am I supposed to use them? Does not using them constitute criticism? Do we really want to measure the number of hearts someone gets? Is there a risk of the "intimidating zero"?
4. The text feels like it is too small compared to the other elements on the page. I'm not sure if the final design will be responsive, but at the moment zooming in and out or resizing the window to change sizes does not fix this issue.

**Comment by Ornataweaver** [comment]
The features that I like:
- simplicity
- command line interface
- very important: I write the code on my computer. I'm not dependent on freecodecamp's in-site text editor. I right it here and I test it here. INDEPENDENT, Confident.
- very pragmatic: exercism does not explain too much from the very first task it gives you. You have to go out and search the web from the very beginning. Thus if you do the first step you will never give up. You are used to leaving and browsing around.
This was the problem freeCodeCamp had, and caused me to abandon it halfway. I grew dependent on it since it had every thing necessary to go on the first 100 hours. I was used to that green website and didn't like to search for the code I needed. So midway I was stuck.

I hope I have helped, since you guys definitely helped me in my life.

**Comment by Ornataweaver** [comment]
The new look seems just like another codewars or codecademy. I like the old look and messiness.

**Comment by Ornataweaver** [comment]
#Independent #Confident

**Comment by Ornataweaver** [comment]
As I'm reading https://github.com/exercism/v2-feedback, I'm beginning to like v2. :) 💯

**Comment by martinfreedman** [comment]
I am fine with the new design. 

I, like many others, miss the cheeky old logo devil/devel and simplicity of it. Goes hand in hand with the site name exercism(exercise). I do not like the new logo and am worried about explanations for the new one like being "more inclusive" and as some have said here "safe space" or "safe haven". 

I fully endorse that this is is not and should not be "competitive" like codewars etc. and the intent (as I read it anyway) was and should be (IMHO) a "cooperative" site.  IMV the operative term, wherever it appears in documentation and in spirit should be "cooperative" rather than "safe", both in contrast to "competitive". The mentoring concept is perfectly aligned with the notion of cooperative. 

It is also a social site - with reviewing, commenting, discussing one another's solutions and learning to be a better coder as a result, an key and important part not just monotonically doing the exercises. In that regard I, just completing the C# stream, (but I am ahead of everyone but the track maintainer @ErikSchierboom) previously always looked at others solutions until I found one that "I thought was great" and commented on others as appropriate. I have gone back to earlier exercises, for both this purpose and to review the readme/test suites to see that any changes are beneficial rather than detrimental to the exercise (in order to help develop the C# track). Again I have commented in order to encourage commenting in return and amongst others. Still my impression is that the "social" aspect as has died down, people are just doing the exercises and moving on, without much interplay between those running in parallel on that track

Do you have any statistics on the amount of comments generated, normalised to number of current users?. I suspect, in the c# track anyway,  factoring in that I joined at a time, IIRC,  there was some widespread publicity for this track, that this level of interaction will have gone down.

Now I am not sure about the mentoring mechanism for V2. 

Is this meant to increase the social aspect, after all it does not encourage or even allow code review ( a very important skill) for non published solutions? IMV far more could be learnt from non-published solutions, which really means allowing learners to comment. I have not seen any flame wars in the c# track, nothing hostile - I did have one dispute with a coder over an additional bonus interpretation of a readme - but that was settled with further coding. And that is it. Moderators should be on every track, in case things do get out of hand and mentors IMV could and should be those moderators That is is in addition to having mentors to aid with coders and _knowing they are authorised to mentor_ - as opposed to being a random other coder - which, presumably is the main and  clear benefit.

Having mentors block progress , excuse my eloquence, is a big No No. Far from being a "safe space" that would be turning this environment into a somewhat "authoritarian" and not cooperative space.

To conclude I am concerned that the new site will overall _reduce_ the social aspect rather then increase it. I long ago thought about gamifying it a la stackoverflow. I never came up with a perfect solution but i was hoping that V2 would have this. It clearly does not and, to the degree, I think, that it is less social than v1, this is I think the main issue for this site. Aesthetics, as great as they are, wont make any difference compared to this.

**Comment by bdjnk** [comment]
I'm just discovering the v2 beta.

The design feels marketing driven and important. These seem detriments.

The original exercism was revolutionary, at its heart a command line tool and your own development environment, the website naught but simple wrapper. A respite from web app centricity.

Nouveau exercism may succeed, but it's a new beast, with a heart of mentorship, not a heart of simplicity. A mentorship model I doubt, and don't appreciate for myself.

Oh well.

**Comment by kytrinyx** [comment]
@bdjnk Thanks for sharing your thoughts.

For what it's worth, the design _is_ much simpler in terms of interactions than the original site, which we hope will work better, even for those who don't enjoy the look particularly much.

Second—you can very easily opt out of mentorship for a track.

**Comment by bdjnk** [comment]
Thank you for the response @kytrinyx.

I appreciate the simplification of navigation, Fundamentally the new website seems more; more featureful, more central, more the primary exercism experience.

Reflective of that, the website code appears more complex. An extra 240KB of JS, so far. Deeper DOM nesting. Abstruse class names and CSS selectors.

I'm still ruminating over the mentorship model.

**Comment by dcustodio** [comment]
I just tried the v2 and it looks good. my thoughts:
- searching for a track could be improved if the tracks are filtered as the user types. 
- when in the mentor page I would like the possibility of giving comments to particular lines of code. 
- I prefer the old logo. 😈

**Comment by kytrinyx** [comment]
> searching for a track could be improved if the tracks are filtered as the user types.

I've added this as a feature request to our internal tracker.

> when in the mentor page I would like the possibility of giving comments to particular lines of code.

I know we've talked about this. There's an additional level of complexity involved in doing it, so it's on the back burner until we get the basics of the user experience right.

**Comment by kytrinyx** [comment]
Thanks for the feedback, comments, and thoughtful discussions.

I'm going to go ahead and close this, as we're no longer looking for the big gut reactions, but rather fixing and fine-tuning details.

Please open issues for the specific things you run into!

💛 🌻 💛

**Comment by Ornataweaver** [comment]
Is this related to GitHub being owned?

**Comment by Ornataweaver** [comment]
Sudden change simultaneous with acquisition of GitHub
