### ISSUE TITLE
Some track icons on mentor dashboard are hard to read

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v2-feedback#102]
Some of the language track icons are hard to read on the mentor dashboard. Case in point: the icons for Java and Scala:

![image](https://user-images.githubusercontent.com/135246/29817019-b75ee7d0-8cb6-11e7-9002-581e820c7360.png)

**Comment by iHiD** [comment]
@ErikSchierboom Thanks. We've already doubled the size of those language icons there. I'll have a look if there's another way we can do this. We've also added the language to the text too since we initially launched, and will be adding filters. Both of those might nullify the problem somewhat, at least for now.

**Comment by iHiD** [comment]
I'm going to close this for now as I think having the language name makes it clear enough. But we'll re-evaluate after launch. Thanks :)
