### ISSUE TITLE
Unusual results from transfer of Scala track progress from v1 to v2

### ISSUE THREAD

**Issue by astradamus** [exercism/v2-feedback#106]
I have completed all of the listed core exercises, yet only some are marked complete, even with incompletes in between them (which, if it's supposed to be successively unlocked as I'm guessing, should be impossible).

However, my progress on 'Extra Exercises' appears to be accurate.

![scalatrackwrong](https://user-images.githubusercontent.com/12521094/30006852-26d0bd06-90b7-11e7-867f-2eb76d54cecf.png)

**Comment by astradamus** [comment]
@kytrinyx This is the wackiness I mentioned, but you know what? Now that I think of it, all of the ones that are marked complete are ones that I completed long ago, and all of the ones that are not marked complete but should be were completed within the last week. So probably the data was copied over before the recent completions.

**Comment by iHiD** [comment]
> (which, if it's supposed to be successively unlocked as I'm guessing, should be impossible).

@astradamus That's actually as we've designed it, as people have completed some exercises in the core but not others as this structure didn't previously exist. You'll notice that there is one "in progress" exercise (Sum of Multiples), which means you can continue the track in a linear way. I think we will maybe reorder the track to always show completed exercises at the top for this scenario. Thoughts?

**Comment by kytrinyx** [comment]
>  I think we will maybe reorder the track to always show completed exercises at the top for this scenario. Thoughts?

That sounds like a really good plan. I'm thinking order by `completed_at ASC, created_at ASC` on the solutions record, that way if they're completed at the same time, then they'll be listed in the order that they were started.

All the exercises that are marked completed by the ETL are using the same completion timestamp, because we don't know when it was actually completed, we only know when they submitted the final iteration—and there could have been discussion after that), and figuring _that_ out was too expensive to be worth it.

**Comment by kytrinyx** [comment]
Also: thanks for the feedback @astradamus, this is a great catch. It looks odd, and we need to fix that.

**Comment by astradamus** [comment]
I like the idea of the core track having not only a set order, but enforcing that order (i.e. no skipping to or even viewing locked exercises). When someone's imported progress defies that order, yeah, just sort the incompletes to the bottom. However, I think as they 'fill the gaps' it should sort in the defined track order as much as possible (i.e. everyone's fully completed core track would show the same order regardless of completion order), so the track page is as consistent as possible between users and to emphasize the importance of the ordering.

EDIT: Oh and also, @iHiD; the way it offers you the next step is perfect--that is, no matter how far ahead the imported progress might be on the track, the next available exercise should be the earliest incomplete on the track.

EDIT2: It occurs to me that people might notice the unusual track reordering for 'grandfathered' users (either on their own track or someone else's) and be pretty confused about the whole thing. Confused enough to necessitate some kind of indication as to what's going on on those exercises or somewhere on the page? Not for me to answer, the design is really gorgeous and that might be too ugly to add. Perhaps leave them out of order and put some kind of highlight/warning sort of thing on the 'completed out of order' exercises? I dunno.

**Comment by kytrinyx** [comment]
> However, I think as they 'fill the gaps' it should sort in the defined track order as much as possible (i.e. everyone's fully completed core track would show the same order regardless of completion order), so the track page is as consistent as possible between users and to emphasize the importance of the ordering.

There's definitely a trade-off here between consistency between users, and allowing tracks to evolve.

My gut instinct is to lean towards assuming that someone did them in the order that was correct at the time that they unlocked the next exercise. This means that if the track maintainers update the order later, then the user would still see the exercises in the order that they did them in. The unfinished exercises would still be able to move around, though, as track maintainers change things.

People are unlikely to compare their tracks to each other, since this is private data.

So I'm kind of thinking: consistency with their "lived experience" (so to speak) would trump consistency between different users.

I'm in no way convinced that I'm right here. Just thinking out loud.

**Comment by astradamus** [comment]
Nope you've addressed all my points. I didn't realize this page was private, that alone pretty much negates most of my thoughts :P  Otherwise yeah, the rest of my points depend on the order being practically sacrosanct and immutable. In light of all that I agree with you.

**Comment by iHiD** [comment]
Triaged to exercism/reboot#131.

**Comment by iHiD** [comment]
@kytrinyx has now fixed this in the new ETL cut, which will be deployed in the coming days/weeks.
