### ISSUE TITLE
Problem Specifications updated after tracks implement it

### ISSUE THREAD

**Issue by Stargator** [exercism/v2-feedback#118]
I was wondering what, if any, approach may change for when the problem specifications may change after a track (or more) have implemented it.

Specifically, I would be interested to know if there will be some kind of notification or automated check of the implementations for changes in the source specification.

And if so, is it up to the track maintainers whether to update? I know there are some allowances given due to differences in languages. So I am just curious if maintainers were interested in tracking these changes, what would be the best approach in v2?

**Comment by kytrinyx** [comment]
I don't believe the process will be different for v1 vs v2 with respect to changes to problem-specifications. It is up to the maintainers to regenerate the READMEs.

That said, this sounds like a discussion worth opening in https://github.com/exercism/discussions/issues to see if we should add some process around how to follow changes.

I'm going to go ahead and close this one, since it's not specific to v2 (but am definitely interested in the broader discussion about keeping things up-to-date).
