### ISSUE TITLE
Publishing multiple iterations

### ISSUE THREAD

**Issue by martinfreedman** [exercism/v2-feedback#129]
In some challenges I have different iterations and my comments refer to other iterations to make a discussion/comparison, often there not being ONE TRUE Way to solve the problem. How do you publish such sets of iterations for review and discussion?

**Comment by kytrinyx** [comment]
@martinfreedman we've designed both the CLI and the backend to handle multiple concurrent iterations for the exact reason that you describe—they're different explorations of the same idea, and there's no one true way.

For the first release of Exercism we won't be enabling the multiple iterations, simply because we need to do additional design work on it to make it understandable, and we don't have the bandwidth to get that done for launch.

**Comment by kytrinyx** [comment]
_This repo is being deprecated. We've imported this issue to the https://github.com/exercism/exercism.io repository._
