### ISSUE TITLE
reaction icon bugs and thoughts on broader design issues.

### ISSUE THREAD

**Issue by bdjnk** [exercism/v2-feedback#146]
The "Genius!" icon is wrapped to the second line on the latest Firefox and on the latest Chrome on an up to date Mac.

<img width="328" alt="screen shot 2018-06-06 at 8 22 46 am" src="https://user-images.githubusercontent.com/620722/41038191-6d015788-6963-11e8-82ba-7e7481aa6fe4.png">

The same issue was raised previously, but only when Google fonts were blocked (#82), which is not the case here.

There are three broad topics, related to this small particular section but applicable to many areas of the new site, I find worth discussing.

## CSS

Fixed widths and floats are being used throughout the new site, including in the above layout. This is an old broken way of writing CSS from the bad times of the early Aughts.

At the very least you should be using `flex`. Truthfully, as this is a site with an audience of developers (and prospective developers), you should be targeting modern browsers and using [`grid`](https://caniuse.com/#feat=css-grid) wherever appropriate.

## UI

The "React to this solution" box is visually separated from the "Solution" box, thus it needs that text. If it were visually joined it would be obvious what you're reacting to.

Worse, the "React to this solution" box appears under every tab, not just the "Solution" tab.

Furthermore, the "Genius!" icon is [a bad icon](https://www.nngroup.com/articles/bad-icons/) because the reference is too esoteric, and because the style is mismatched and much too detailed.

Lastly, there are too many reaction types, and not enough clarity on what distinguishes between them. It might be worthwhile to investigate the trade-offs between [simplicity and choices](https://www.nngroup.com/articles/simplicity-vs-choice/). 

## Interactions

Deselecting a reaction partially appears to work, but actually doesn't. The header's reactions bar's numbers change, but the highlight doesn't. Re-selecting the reaction doesn't work, and refreshing the page shows it was never meaningfully deselected.

Selecting an alternative reaction does survive a refresh, but as before the header's reactions bar's highlight does not change.

This was ostensibly resolved (#78) but appears to remain, as you can see http://recordit.co/TucnuqOqzl

---

All of this makes me hope there is a serious detail level redesign underway, and plans for a comprehensive refactoring effort.

**Comment by iHiD** [comment]
> The "Genius!" icon is wrapped to the second line on the latest Firefox and on the latest Chrome on an up to date Mac.

We've changed the fonts across the site and things need realigning as a result. We have an open action for this before launch. Thanks.

> Deselecting a reaction partially appears to work, but actually doesn't. The header's reactions bar's numbers change, but the highlight doesn't. Re-selecting the reaction doesn't work, and refreshing the page shows it was never meaningfully deselected.

Thanks. I will investigate.

> Furthermore, the "Genius!" icon is a bad icon because the reference is too esoteric, and because the style is mismatched and much too detailed.

I disagree, but will pass this back to the product team for their thoughts.

> Fixed widths and floats are being used throughout the new site, including in the above layout. This is an old broken way of writing CSS from the bad times of the early Aughts....

While I appreciate that you want to best for exercism, I don't think the style of the HTML/CSS matters to how the site helps people to learn to code, and as a result, I'm not massively open to discussion on it. If there are bugs then please please report them as that's super-helpful, but fundamentally, if this is functional and looks professional, then I'm content for now.

> Truthfully, as this is a site with an audience of developers (and prospective developers), you should be targeting modern browsers 

Developers and prospective developers aren't necessarily rich and don't necessarily have access to the latest technology. I care more about supporting the most people possible (and therefore older browsers) than I do about using the most modern techniques (e.g. flex). For example, IE11 still does not support flexbox without bugs, and therefore I chose to make a site that works without hacks for the 4,000 people have used exercism on IE11 in the last 12 months, rather than use the latest techniques. I don't using long-standing technologies makes the product any less usable than using the latest.

> All of this makes me hope there is a serious detail level redesign underway, and plans for a comprehensive refactoring effort.

There is neither, because I don't see the value of such a refactor to the goals of exercism right now. But maybe further down the line we will freshen things up.

**Comment by bdjnk** [comment]
> I don't think the style of the HTML/CSS matters to how the site helps people to learn to code, and as a result

Not directly, no. However a well designed product will have fewer bugs and work better more often for more users.

That said, I understand and will restrict future comments here to actual functional bugs.

> Developers and prospective developers aren't necessarily rich and don't necessarily have access to the latest technology.

The latest versions of all major browsers are completely free and most have recently been getting less resource intensive.

> IE11 still does not support flexbox without bugs

While this is true, I work on an enterprise web application targeting IE11. We use `flex` extensively with only minor inconveniences.

**Comment by kytrinyx** [comment]
_This repo is being deprecated. We've imported this issue to the https://github.com/exercism/exercism.io repository._
