### ISSUE TITLE
exercise icons: a couple minor issues

### ISSUE THREAD

**Issue by rpottsoh** [exercism/v2-feedback#147]
Several exercises lack an icon and several are using the same icon.

**Lacking an Icon:**

- [ ] Yacht
- [ ] Dot Dsl
- [ ] Isbn Verifier
- [ ] Rational Numbers
- [ ] Armstrong Numbers
- [ ] Reverse String

**Duplicate Icon:**
- [ ] All Your Base
- [ ] Binary
- [ ] Trinary
- [ ] Octal
- [ ] Hexadecimal

There may be more with duplicate icon usage, these were easy ones to spot.  I didn't see this as an open/closed issue so want to bring it to your attention just in case you were not aware.

**Comment by kytrinyx** [comment]
Thanks! We are tracking this one internally (the missing icons are new exercises since we did the original round of icon design). We have an update to the binary, trinary, octal, and hexadecimal exercises to add the base number in as part of the icon. All four of those are deprecated in favor of all your base.

**Comment by rpottsoh** [comment]
👍 
You are probably tracking this too, then.  There are several tracks lacking icons as well.
I'll go ahead and close this.

**Comment by kytrinyx** [comment]
> There are several tracks lacking icons as well.

Yepp, we have an open issue for that, as well.
