### ISSUE TITLE
mentorcism: On joining plsql, clojure and elisp tracks, get 404 error

### ISSUE THREAD

**Issue by amoradell** [exercism/v2-feedback#165]
I tried to join these tracks and got 404 error

After joining all tracks, only these three are unknown

**Comment by iHiD** [comment]
@amoradell Thanks. Nice catch. 

The reason is that none of the tracks are ready for launch, and the code is now being less forgiving about this. These are the outstanding issues for these three tracks.

https://github.com/exercism/plsql/issues/39
https://github.com/exercism/elisp/issues/88
https://github.com/exercism/clojure/issues/236

@kytrinyx I'm assigning this to you for your visibility, but feel free to close it, as we're tracking this on meta.

**Comment by amoradell** [comment]
I could join plsql and downloaded hello-world but no test file and solution. Only readme.md

**Comment by iHiD** [comment]
@amoradell Thanks. I readded *some* defensiveness to make these tracks functional on the mentors-beta which is why you can now access them. With regards to the missing test file and solution, you should have got the [files here](https://github.com/exercism/plsql/tree/master/exercises/hello-world) I think. Maybe @kytrinyx has some knowledge or ideas?

**Comment by kytrinyx** [comment]
_This repo is being deprecated. We've imported this issue to the https://github.com/exercism/exercism.io repository._
