### ISSUE TITLE
[mentorcism] mentorcism download error message should prompt user to join a track before downloading exercises

### ISSUE THREAD

**Issue by aldraco** [exercism/v2-feedback#174]
To recreate: 
Select a track you have not currently joined on Mentors Beta site. 
run: `mentorcism download hello-world --track=ruby  `

Result: `Error: solution not found `

To fix: Join the track on the mentors beta site, and the download command works fine. 

Manually creating the directory locally did not solve the issue; the error seems to be generated in the site's API.

**Comment by iHiD** [comment]
Hi @aldraco. As far as I can tell, what you've described is the expected behaviour. You cannot download solutions from tracks you have not started. 

See the posts here:
https://exercism-mentors.slack.com/archives/CAQP7JL3T/p1529686720000506
https://exercism-mentors.slack.com/archives/CAQP7JL3T/p1529683065000711

Is there something I'm misunderstanding in what you're saying? Thanks :)

**Comment by aldraco** [comment]
Thank you, that specific requirement was not clear from the error message generated in the CLI. I see there is already discussion about adding more error messages, so that would address it well enough, I think.

**Comment by iHiD** [comment]
OK cool. I think this is something that will trip-up seasoned Exercism users who are used to the original exercism way, but will be more clear to new users who no no-other way. We're thinking of having a page for "What's changed?" when someone from v1 logs into v2. Maybe we should put some more information around this on there, as this seems to have been the most frequent stumbling block for people so far?

Are you ok for me to close this as a duplicate of #149?

**Comment by aldraco** [comment]
Ah yes, apologies I did not see that issue already addressed it. Thank you!

I agree, a "what's changed" would be nice to have.

**Comment by rpottsoh** [comment]
@iHiD to me `mentorcism download hello-world --track=ruby` isn't downloading the solution, it is downloading the exercise as a student, to be solved.  And, as you have already stated, the site expects the student to signal their intent to complete an exercise before the CLI is allowed to download it.

As a mentor, if I want to download a student's solution to review locally I would want to use the --uuid flag along with the UUID for the student's solution.  I am expecting I would not need to have already submitted a solution of my own for the given exercise in order to be able to download it for the sake of mentoring it.  Am I wrong in this assumption?  I have not had the opportunity to try --UUID.  
 
I now recognize that this comment may be better served in another issue.  I'm happy to relocate it if you think it worthwhile.

**Comment by iHiD** [comment]
@aldraco No need to apologise. Thanks for opening!

> As a mentor, if I want to download a student's solution to review locally I would want to use the --uuid flag along with the UUID for the student's solution. I am expecting I would not need to have already submitted a solution of my own for the given exercise in order to be able to download it for the sake of mentoring it.

@rpottsoh Your assumption is correct :)
