### ISSUE TITLE
Solution Pane Too Narrow (aka I want the old V1 'wide view' button back)

### ISSUE THREAD

**Issue by AtelesPaniscus** [exercism/v2-feedback#183]
Reference:
https://mentors-beta.exercism.io/mentor/solutions/4ab7fada752b46e983c306a35b05e6ff

Can you read this without a copy/paste to an editor ?  I can't.

The old interface has a 'widen button' that hide the comment.  I liked that.  I seemed, at the time, like a clever piece of ergonomics not a Plan D bodge (kludge).

I can't widen the solution box.  The whole Exercism uses only half my screen width.  How much technology have I at my finger tips ?  Is this really the ergonomic best we can do ?

Copy/paste just to read a solution is not consistent with giving quality assistance on a budget of an hour a week.

**Comment by NobbZ** [comment]
Well, I like having the comment box side by side to the code I comment.

Having to scroll back and forth between both when commenting is distracting and leads to errors in the comments.

But as you do, I'd really welcome a wider code pane.

**Comment by AtelesPaniscus** [comment]
I too like having them side-by-side as I comment but I also just study the solution first.

If I'm going to copy/paste one, I'd rather write the comments where I have spell checker.  It seems the old interface had auto-spell checking on and the new one doesn't.  I guess that is a separate issue.

**Comment by iHiD** [comment]
@AtelesPaniscus I appreciate your concerns and this is something we can discuss/consider.

However, using language like "a Plan D bodge (kludge)", "is this really the ergonomic best we can do ?" is not in alignment with Exercism's values or the quality of empathetic discussion and feedback we expect, especially from our mentors. The team building this new website have put in thousands of unpaid hours of work into doing so and the negativity in your post is disheartening to all of us. 

While I genuinely appreciate you opening issues and raising these points, please can you do so in a way that is respectful and in line with our [Code of Conduct](https://github.com/exercism/exercism.io/blob/master/CODE_OF_CONDUCT.md), and that encourages the team to do work on this product rather than relaxing in our evenings. Thank you.

**Comment by AtelesPaniscus** [comment]
My apologies for breaking your code of conduct.

I too am disheartened.  I have put many of my free hours into giving students feedback.  I grew fond, perhaps too fond, of the old Exercism site perhaps because it was not like other web sites.

If this is beta testing then the features from the old site that I appreciated so much have been omitted by design and are not coming back.

There are two core things I need to be able to do to mentor, everything else is nice to have.  I need to be able to read the submission and I need to be able to write, spell check, review and edit my comments over and over.

I promised myself I would try mentoring on your new site.  I expect, as with other web sites, I will spend most of my time working in a text editor and copying/pasting to/from the finished GUI.  That would be a great shame.

**Comment by kytrinyx** [comment]
@AtelesPaniscus -- there are some features that are different by design, there are a number of features that we will be finishing and developing over the next few months.

> There are two core things I need to be able to do to mentor, everything else is nice to have. I need to be able to read the submission and I need to be able to write, spell check, review and edit my comments over and over.

I'm not sure what we have done that has convinced you that we are not going to make it possible to do these two things. It seems quite key to anyone's workflow.

Based on the above discussion, I'd like to ask you for two favors:

1. When you are having trouble doing a thing that is core to your workflow, please make the assumption that we probably want the best experience. Please assume that we are smart and competent. When  things are imperfect, please assume that we have good reasons for it. Those reasons might be by design, but they also might not be that we just haven't gotten to it yet, or that our workflows are different and that we are unaware of your use case, and that if we can have discussion about it, we might very well agree that the problem you describe is something that we would like to fix.
1. When you are trying to achieve something, then please describe what you are trying to achieve, rather than going straight to suggesting a particular solution. This lets us discuss the problem itself with you, and ask better, more useful questions, rather than having to try to reverse engineer a guess about what the underlying problem is.

**Comment by AtelesPaniscus** [comment]
Thank you for your feedback.  I feel honoured somehow.  I wish I could reply succinctly, constructively, collaboratively and without sarcasm.

I am not 'like minded'.  To me that phrase is linked to 'group think' and the Bay of Pigs Débâcle, Cuban Missile Crisis and all that ancient history only I am old enough to have been in the US at the time.   Group think is still behind many of the stupid mistakes made by groups of intelligent, experienced and dedicated people in business and politics the world over.  That's folks - they never learn.

I have trouble seeing a naked, wrinkly, old man as an emperor in fine new clothes.  At work, those who want to save time and money love my insights, those who want to save face hate them.  Your new site will be launched.  It is too late for any one to question whether it is ready.  I certainly do not but I want to close my eyes so I can't see.  Qué sera, sera.  I wish you all the best.

I did not think that I was suggesting a particular solution.  I am an analyst, not an engineer.  I was trying to understand the new UI and its workflow.  I do not know what I'm supposed to be assessing and, yes, that is frustrating.  I accept now that that is not my job and I am trying to keep off slack and github and am just trying to grok the workflow from using it.

I too am smart and competent.  Do not think I underestimate you.  My great mistake, which I repeat over and over again, is assuming, until proven otherwise, that people I come in contact with as a smart and as competent as I.  My great frustration in life, in and out of work, is not being able to explain what I 'get' to others who do not.  I do not hide behind the word 'intuitive' because I can see that it certainly is not to them and I feel insulted when folk use the term on me but I keep being told GUIs are 'intuitive' (I think they think the word means something that cannot be explained in words).  To me GUIs are not intuitive and I was really not expecting your new one to be but I have not complained about this.

I know you are a small team and you do the work in your free time for free.  I have not seen an appeal for developers but when you appealed for mentors I thought my forty years programming experience might be worth something.  I am out of work so I can spend a lot of time on it.  I was without broadband for a couple of weeks but I did not want to get left behind so I took a laptop to a café twice a day.  That was fraught as the laptop was old and not really up to the task.  When I got broadband back I expected things to be 100% better but I found ... well, please bear with me, ... I have been 'mentoring' unofficially on the Erlang track V1 for some time.  What you see as features you haven't 'gotten to' are features I saw as withdrawn and I expressed disappointment in language less than diplomatic.  I apologise for being months ahead of you.

I apologise for having a different understanding of beta testing than you do.  I was expecting the workflow to be implemented, perhaps with bits not working properly, but not for bits to be missing.  I am really sorry about that.  I think very highly of V1 but I have no idea what to make of V2 at the moment.  Next time perhaps a pop up or tool tip that reads "Coming soon" would help.

The V1 interface has a 'wide view' button that I often use when reviewing code.  This hides the comment so it is a trade-off and possibly an afterthought.  A bodge, perhaps, that I am very fond of.  Again my apologies if you find the term offensive but I very much liked that button and am sorry to see it go.  So I copy/paste the code into an editor where I can see at least each line in its entirety.  The current Solution box is only 64 characters wide and I've found the interface very 'responsive' but I cannot get the Solution box to show more code.  Sadly by the time that feature comes along I will either be set in my ways or will have found something else to spend too much time on.

I need a spell checker for my comments and my browser used to give that with V1, underlining typos as I typed.  It does not with V2.  I suspect the comment box is now an active component that swallows characters as they are typed and unless the framework you have chosen has a spell checker feature you have not turned on yet, there will be little you can do to add that feature later.  Or perhaps it is just middleware.

I remember when these WYSIWG text boxes first came out.  I used to disable them.  Now in several web-based applications I've no spell checker, copy/paste does not work 'intuitively' and I have to use HTML to get a blank line between paragraphs.  I don't hold that against the Exercism project or the team or its members.  I just prefer the V1 interface even though I can see that hurts.

One last remark.  I have signed to mentor three tracks that are under represented.  My budget is one exercise on each track per week.  That would be 20 minutes for each exercise if I stick to the 1 hour you have asked for.  I think that is tight:  I expect to overrun by 200% and if I don't approve a submission first time that will be yet more extra time.  That is based on my experience.  I have learnt from this beta trial that trying to mentor an exercise that I have not solved (on this track) is not a good idea so I have to work through all the exercises as a student too.  I saw somewhere that your estimates of how many mentors you need are based on 5 minutes a pop.  I am not disputing your calculations.  I am scared - I mean frightened - of what will happen if so many of the ra-ra-ra mentors who have signed up find mentoring requires much more of their time than they have thought and drop out.  The GUI I don't really care about.  Copy/paste in and out of the GUI I can cope with.  I do care about the quality of the mentoring.  I am really concerned that all involved are too optimistic about how much they can do with too little time.  But that's folks too - eternal optimists (even me in my own way).

All the best to you and your team.

**Comment by NobbZ** [comment]
As I already said, I miss some wider view as well.

But there is really no need for copy/pasting the code. You can `mentorcism download --uuid=…` which will download the submission alongside with its associated tests, which you then can run locally.

You can also open the code in your favorite editor, having your favorite colorschema in the highlighting, open another window doing the comments, markdown highlighting + spellchecker enabled. This is where one needs to copy/paste then though… For the old exercism (which uses a `textarea` instead of JavaScript) I have an browser addon which can open the textbox in emacs, associate the MD highlighter, activate the spellchecker and even injects some snippet commands related to the track I am currently on. But this plugin doesn't work with the new JavaScriptified comment box. But this is another issue…

So the proper (intended) flow by design is probably to use the CLI to download the code and actually play with it locally.

But I think this were much more obvious, if there actually were a copy pastable snippet to download the exercise in question…

**Comment by AtelesPaniscus** [comment]
@NobbZ thank you very much for that.  I think will find downloading solutions this way very handy.

The right information out of context can be meaningless.  In the right context you just say "Ah, of course.  Why didn't I think of that."

**Comment by kytrinyx** [comment]
Summarized in https://github.com/exercism/exercism.io/issues/3887
