### ISSUE TITLE
[mentorcism] User reflections do not parse markdown

### ISSUE THREAD

**Issue by JoelQ** [exercism/v2-feedback#185]
I left some thoughts when publishing a shared solution. However the rendered text does not seem to be processed as markdown. Note the backticks in the image below.

![exercism 2018-06-27 11-28-59](https://user-images.githubusercontent.com/1006966/41983970-750dc97a-79fd-11e8-8adb-7219fe672638.jpg)

**Comment by iHiD** [comment]
I think we'd actually planned for this not to be markdown. But your example suggests strongly that it should be. I'll add it to the plan. Thanks.

**Comment by carolineschnapp** [comment]
👍 for markdown rendering in the User reflection, for code snippets, bold, italic, and also for links to complementary documentation.

**Comment by NobbZ** [comment]
> I think we'd actually planned for this not to be markdown.

Please do not do this anywhere…

The principle of least surprise tells us, if a certain type of markup is allowed in a box that is used regularly, you expect the same markup to work everywhere unless stated otherwise.

So if markdown is removed from some inputs intentionally, please label those inputs.

**Comment by kytrinyx** [comment]
_This repo is being deprecated. We've imported this issue to the https://github.com/exercism/exercism.io repository._
