### ISSUE TITLE
Separate 'Complete Exercise' from 'Comment' button

### ISSUE THREAD

**Issue by MarcosX** [exercism/v2-feedback#187]
When writing a comment the 'Complete Exercise' button bellow the text area is highlighted and may induce people to clicking on it while trying to submit a comment, specially since the 'Comment' button looks like a "secondary button".

<img width="527" alt="screen shot 2018-06-27 at 13 37 02" src="https://user-images.githubusercontent.com/856376/41987411-6dd13fcc-7a0f-11e8-8b00-5eda4d296bb2.png">

I think that maybe the two buttons could be placed differently on the screen, maybe above the 'Mentor Discussion' section or something (I'm not an UX person so there are probably better ways to achieve this :p),

**Comment by iHiD** [comment]
Which page is this on? 

I *think* this is on your own solution where the mentor has approved your exercise and therefore the primary action is to complete the exercise. Could you send me a full-screen screenshot pls?

**Comment by iHiD** [comment]
Just seen #186. Maybe we should move that button from there altogether. I remember we struggled with where to put it because there's already a few CTAs. I wonder about maybe not showing the comment box by default once the exercise has been approved and instead having two buttons for Complete and a secondary action for adding a comment, which shows the box. We'll discuss internally. Thanks.

**Comment by iHiD** [comment]
I've now separated this button out (on master).

<img width="1171" alt="screen shot 2018-07-01 at 14 48 01" src="https://user-images.githubusercontent.com/286476/42135054-cc5c2986-7d3d-11e8-9799-e07b4a74b213.png">

Thanks for the super-helpful suggestions!
