### ISSUE TITLE
Syntax highlighting is missing for C++ track

### ISSUE THREAD

**Issue by pacmancoder** [exercism/v2-feedback#194]
I tried to upload my solutions to mentors-beta website and found that C++ syntax is not highlighted

![default](https://user-images.githubusercontent.com/3994505/42241875-c4262252-7f14-11e8-8f3f-a03969a6cc3d.png)

**Comment by pacmancoder** [comment]
Interesting. Looks like as side-effect discussions are also have become broken.
https://mentors-beta.exercism.io/mentor/solutions/5066868db29a4405a7679512a07c0989

If you press "Comment", visually nothing is changing, but after page reload, comment can be seen.

**Comment by iHiD** [comment]
Hi @pacmancoder Thanks for raising the issue.

There is a parallel (closed) issue [here](https://github.com/exercism/v2-feedback/issues/170) for `lisp` 

If you get 10mins and would like to get into the website codebase, maybe you could add a [PR like this](https://github.com/exercism/prototype/pull/75) which will probably fix it. Otherwise, we'll get round to it before launch. Thanks! :)
