### ISSUE TITLE
Layout is not mobile-optimized

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v2-feedback#34]
If you resize your browser (which simulates being on a mobile device), the content does not *flow* correctly. Example:

![image](https://user-images.githubusercontent.com/135246/29488970-e22b3c8c-8515-11e7-8674-551ec96fae87.png)

Here you can see that the sidebar is cut in half, and the footer does not break but instead continues horizontally.

The same goes for other pages, like the language track's page:

![image](https://user-images.githubusercontent.com/135246/29488979-0a072cd4-8516-11e7-8d42-92ab7ac63827.png)

**Comment by kytrinyx** [comment]
@ErikSchierboom Yeah, we've not tackled mobile/tablet layouts at all yet.

**Comment by iHiD** [comment]
Thanks for checking :)

Three thoughts:
1) We've taken the attitude that people aren't going to be reviewing code etc on their phones, so that mobile doesn't matter a huge amount. 90% of sessions on Exercism are on desktop atm. However, it would be nice to have the external pages mobile-friendly for opening on social media.
2) The side won't break on mobile, it will just look really small, but it is zoomable into and usable if it needs to be.
3) The site is built using a responsive grid that's just currently turned off, so it will/would be quite simple to make the whole thing mobile-friendly. However, I want to get the final thing right on desktop first before going through the process.

**Comment by ErikSchierboom** [comment]
Excellent points. Making it be perfect for the desktop is indeed much more important, so I don't expect a mobile-friendly version to come soon. It's just something I noted, especially since, as you say, most websites nowadays already use a responsive grid.
