### ISSUE TITLE
Custom snippet does not get displayed

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v2-feedback#40]
For the C#, we added a custom snippet to be displayed on the track's page according to: https://github.com/exercism/discussions/issues/173 This means we added a docs/SNIPPET.txt file, but this snippet does not get displayed.

**Comment by iHiD** [comment]
Great. Thanks for letting us know. @ccare will work this out on Tuesday.

**Comment by NobbZ** [comment]
As I just realise, a fix of this seems crucial, since in Haskell the build-tools yaml is shown ;) Perhaps other tracks are affected by similar problems as well?

Candidates might be erlang, java, rust, lfe, and other tools that use some file which describes the build while the actual sourcecode gets burried in sub folders.

**Comment by iHiD** [comment]
Ha. Yes.

**Comment by kytrinyx** [comment]
We can use the config's `solution_pattern` to identify the correct file from the exercise where the SNIPPET file doesn't exist.

**Comment by Insti** [comment]
Would it be simpler to just require a SNIPPET file?

**Comment by iHiD** [comment]
> Would it be simpler to just require a SNIPPET file?

Yes :) But along with all the `config.json` changes and stuff, there's a lot for maintainers to do, so we're trying to lighten that load as much as possible. So 100% we will eventually require all tracks to have the SNIPPET file, but a good fallback that doesn't block everything for now would be nice too. 

Maybe we give it 7 days for everyone to get a SNIPPET file in place, then take stock of where we're at, before we invest time into writing code to solve this?

**Comment by ilya-khadykin** [comment]
> Maybe we give it 7 days for everyone to get a SNIPPET file in place, then take stock of where we're at, before we invest time into writing code to solve this?

I guess it's a good idea to have a separate issue for this with all tracks as sub issues to check. It will add visibility

**Comment by kytrinyx** [comment]
I've opened a meta issue for this: https://github.com/exercism/meta/issues/89 I'll go ahead and do it today.

**Comment by iHiD** [comment]
@ErikSchierboom Is the file now displaying ok, and if so can we close this pls, as we're tracking the bigger conversation in meta? Thanks.

**Comment by ErikSchierboom** [comment]
@iHiD I'm afraid not. This is the [snippet file](https://github.com/exercism/csharp/blob/master/docs/SNIPPET.txt)'s contents:

```

class HelloWorld
{
    string Hello()
    {
        return "Hello, world!";
    }
} 
```

And this is what is rendered:

![image](https://user-images.githubusercontent.com/135246/29585285-e0080dd6-8786-11e7-97b9-880cffc7ef5d.png)

**Comment by iHiD** [comment]
@ErikSchierboom Thanks for checking. I was lazy and presumed that because there was "some" code it was the "right" code. My bad. I know @ccare and @kntsoriano have been working to handle changes of webhooks, so it might be they've decided not to fix what was every broken in the original code. I'll pester you again when @ccare tells me it's all working :)

**Comment by ccare** [comment]
@ErikSchierboom @iHiD I believe this should now be up to date. Thanks for spotting this, there was a bug causing the sync code to fall over.

**Comment by ErikSchierboom** [comment]
It's working! Thanks.
