### ISSUE TITLE
CLI on Windows: unable to submit without arguments

### ISSUE THREAD

**Issue by kytrinyx** [exercism/v2-feedback#42]
From @jonmcalder:

> From Git Bash:
> 
> Running nextercism submit from within exercise directory does not work. The error returned is:
> `. not within workspace`

It does seem like running `nextercism submit` without arguments does work from the command prompt and with Powershell.

**Comment by kytrinyx** [comment]
I thought I had built a version `v3.0.0-alpha.3` that fixed this, but I just checked the definition of the submit command in that tag, and it doesn't have the change.

I'm going to build a thing unofficially (not an actual release) to see if we've got this one fixed. One sec.

**Comment by kytrinyx** [comment]
@jonmcalder Would you try with one of these?

- https://www.dropbox.com/s/qepgxsy2knx5ypx/nextercism-windows-64bit.zip?dl=0
- https://www.dropbox.com/s/pciav0jkvdv34g6/nextercism-windows-32bit.zip?dl=0

(not sure if you need the 64 bit version or the 32 bit version)

**Comment by kytrinyx** [comment]
Note—I am only addressing the `. not in workspace` error, not any of the path issues.

**Comment by jonmcalder** [comment]
Ok I've just re-tested with the 64-bit version above.

In the process I discovered (quite unexpectedly) that this issue is actually directly linked with #44. The failure is not actually linked to Git Bash - this appears to have been coincidental in my initial testing and I jumped to the wrong conclusion. Apologies.

First note that the directory I am targeting is `C:/Users/Jon/nextercism/r/leap`.

Turns out that in any of the 3 shells if I do: 
```
cd c:/users/jon/nextercism/r/leap
nextercism submit
```

The latter command fails - since the system returns the lowercase filepath as initially entered, rather than the (actual) case-sensitive version of the file path.

If I instead do:
```
cd C:/Users/Jon/nextercism/r/leap
nextercism submit
```

Then it works fine. In all 3 shells.

Similarly I can use `cd ~/nextercism/r/leap` or `cd C:\\Users\\Jon\\nextercism\\r\\leap` followed by `nextercism submit` and this executes just fine.

So either this was never actually a separate issue (i.e it was just #44 masquerading as a separate issue), or you have fixed it with the update above.

Based on this, my understanding is that once you can address #44, you might be able to close this issue too (that is, assuming that the parsing/handling of case-sensitivity in the filepath is done both when it is explicitly provided as an argument and when it is inherited/inferred from the current path on the system).

**Comment by kytrinyx** [comment]
I think I fixed it, which uncovered the next layer and it's exhibiting the same problem as #44 

I'll leave this open until we can prove definitively that it's fixed.

Thanks for the additional information!
