### ISSUE TITLE
CLI on Windows: Path is case sensitive

### ISSUE THREAD

**Issue by kytrinyx** [exercism/v2-feedback#44]
From @jonmcalder:

> From Command Prompt and Powershell:
> 
> [...]
> The file path is also case sensitive

@jonmcalder: does this mean that the path is not case sensitive from Git Bash?

**Comment by kytrinyx** [comment]
@jonmcalder - would you help me construct a typical use case for the case insensitive issue?

Here's my first attempt:

The actual file tree:

```
CaseInsensitive/
└── creatures
    └── horse
        └── Horse.txt
```

Given the command `nextercism submit caseinsensitive/creatures/horse/horse.txt` would you expect this to find the right file and submit it?

Some notes to self: Go has a `path` package and a `filepath` package. Both have a `Match()` function. `path` is for conceptual paths, whereas `filepath` is for os paths.

**Comment by NobbZ** [comment]
For windows that should find `horse.txt` and submit it. Recent windows systems (about since XP) are casepreserving but -insensitive (before that everything got normalized into lowercase AFAIR).

From windows point of view `TheSame`, `thesame`, and `ThEsAmE` are exactly that, the same. AFAIK this is similar on Macs.

Whatever casing you use when creating the folder/file will be used when displaying the filename, you can even rename from `name` to `NAME` to change how it is displayed, the file will still be accessible by both names.

Therefore, the common windows user doesn't care for casing of a path or filename.

**Comment by jonmcalder** [comment]
Sorry for not being clearer previously. The `nextercism submit` (with no file path specified) issue applies only to Git Bash.

The case sensitivity and file path separator issues apply to all three.

The use case you suggest above looks good to me. The only thing I can't quite recall is whether filenames themselves are normally case sensitive in these shells on Windows. But the directories normally aren't e.g. in Git Bash if you tab to autocomplete a directory name within a `cd` command or something like that its usually lower case even if the actual directories names are capitalized on the systems file path.

e.g. having to specify uppercase `C:\Users\` shouldn't be necessary (which I had to do with the CLI to get it to work)

Can't really offer any more help until later when I get home to a computer though.

**Comment by kytrinyx** [comment]
> From windows point of view TheSame, thesame, and ThEsAmE are exactly that, the same. AFAIK this is similar on Macs.

I think you may be right on default Mac setups, but I believe I've set some preference somewhere in mine so that it is case insensitive.

> having to specify uppercase C:\Users\ shouldn't be necessary

So you would type `c:\users\` and it would find it?

**Comment by NobbZ** [comment]
> I think you may be right on default Mac setups, but I believe I've set some preference somewhere in mine so that it is case insensitive

Case insensitivity is exactly the behaviour described.

**Comment by kytrinyx** [comment]
Sorry, typo. The filesystem on my Mac is case sensitive, not case insensitive.

**Comment by jonmcalder** [comment]
> So you would type c:\users\ and it would find it?

Yes in Powershell and Command Prompt the above e.g. `cd c:\users\` would work, even if (strictly) the directory is actually `C:\Users\`

Git Bash isn't case-sensitive either (so the lower case `users` is fine), but usually won't accept single `\` as a file separator since this is treated as an escape character.

This means `cd c:\users\` won't work in Git Bash since it is evaluated as `cd c:users`. If you pass the filepath as an explicit string argument it works though: `cd 'c:\users\'`. Alternatively `cd c:\\users\\` or `cd c:/users/`
