### ISSUE TITLE
CLI submit will submit many files

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v2-feedback#48]
I was just testing the CLI on MacOS by trying to submit something in the C# track. What I did is I ran the following command: `exercism submit` (without any arguments). This showed a 500 internal server error, but it actually did submit a lot of content: https://v2.exercism.io/my/solutions/564c3281-e20a-4589-bc9e-4c9ff7c0956e?iteration_idx=1

How can a track specify which files should and which should not be sent?

**Comment by kytrinyx** [comment]
Right now I'm not sure if the filtering is a part of the alpha CLI release or not, but we filter out anything that is in the `test_pattern`. We can add patterns to ignore if we need to.

**Comment by kytrinyx** [comment]
By "add patterns" I mean—we can add an extra field to the config.json that is a list of patterns to ignore.

**Comment by ErikSchierboom** [comment]
Maybe that would be useful. What is the purpose of the `test_pattern`field, is it just to filter out files?

**Comment by kytrinyx** [comment]
`test_pattern` is to identify which file(s) are for the test suite. We use it on the site to display the test separate from the readme in the instructions, and in the old CLI to warn before you submit a test file, and in Configlet to make sure that an exercise actually has a test.

**Comment by ErikSchierboom** [comment]
Ah okay, then a new field would probably be needed. Or can we use the `solution_pattern` field?

**Comment by kytrinyx** [comment]
`solution_pattern` is for the example solution. That should already be filtered out before it gets delivered.

**Comment by tleen** [comment]
We may want to filter out other files too? Like the ones supplied with the exercise, the README... I have seen them inadvertently submitted by, uh, a friend.

**Comment by kytrinyx** [comment]
I should be filtering out all *md files at the moment, but yeah, I really do think we need to be able to specify other ignore patterns.

**Comment by kytrinyx** [comment]
Dangit. I just checked the current release and it doesn't have that code in it. One sec. Let me go get that.

**Comment by kytrinyx** [comment]
Wait. No, it's there. I was looking in the wrong file.

OK, so bottom line is:

Currently we are filtering out the following patterns on submit:

- `".*[.]md"`
- `"[.]solution[.]json"`
- whatever is in `test_pattern` in the track config

So. Shall we have a field called `ignore_on_submit_patterns: [...]` or some such thing?

**Comment by NobbZ** [comment]
What do you mean by `[.]`?

**Comment by kytrinyx** [comment]
It's a character group with only a period in it. Equivalent to `"\\."`.

**Comment by ErikSchierboom** [comment]
> So. Shall we have a field called ignore_on_submit_patterns: [...] or some such thing?

+1

**Comment by NobbZ** [comment]
> It's a character group with only a period in it. Equivalent to `"\\."`.

Oh, a regular expression… I've tried to make sense of it as a shell-glob…

**Comment by kytrinyx** [comment]
Yeah, sorry—totally forgot to mention that. The `*_pattern` fields in the config are strings that get compiled into a regular expression.

**Comment by tleen** [comment]
I don't think the *.md pattern is taking:

```sh
$ nextercism submit README.md 
Submitted. View at https://v2.exercism.io/my/solutions/11ec2ef9-55d1-44f7-af52-4ca8721d029a
```

When I view the solution it is the README.

**Comment by kytrinyx** [comment]
I can't visit that until you publish it. I can check the db, though.

Which version of the CLI are you on?

**Comment by tleen** [comment]
[I think its published now?](https://v2.exercism.io/tracks/go/exercises/hello-world/solutions/7b976393-05d2-4f2b-b421-bd8d416705c1)

I'm on ```version 3.0.0-alpha.3 ```

**Comment by kytrinyx** [comment]
> I think its published now?

It is, indeed! The README is not submitted in that solution, though. Where are you seeing it?

**Comment by kytrinyx** [comment]
> nextercism submit README.md 

@tleen If you explicitly submit files, we don't filter them, only if you submit a whole directory.

**Comment by tleen** [comment]
Ok I republished. [This is it](https://v2.exercism.io/tracks/go/exercises/hello-world/solutions/7b976393-05d2-4f2b-b421-bd8d416705c1).

> @tleen If you explicitly submit files, we don't filter them, only if you submit a whole directory.

Shouldn't things like README.md get filtered?

**Comment by kytrinyx** [comment]
> Shouldn't things like README.md get filtered?

I'm assuming that if you explicitly submit a given file, then you're doing it for a reason. Usually this would be a test suite where you've added tests, but I feel like I can't guess at people's intentions if they're saying "submit exactly these files".

For the one that you're showing me, did you submit the directory or explicit files?

**Comment by tleen** [comment]
Explicit files. I would figure a submit block would exist globally, not just for ```.```. 

Seems more a case a user would try to submit a file unintentionally (thinking a Go test file, which is very tab-complete close to the name of the exercise file) then they would submit one that would otherwise be blocked. I've done it.

**Comment by kytrinyx** [comment]
> Seems more a case a user would try to submit a file unintentionally

Ah, ok, that makes a ton of sense.

How about having an interactive dialog `did you really mean to submit X?`?

And probably a `--force` flag if you don't want the interactive dialog but know that you're going to be doing something that the CLI will be suspicious of.

**Comment by tleen** [comment]
It is reasonable, I figure a lot of the users may be using the CLI for the first time. I can't quite find where I did it, but I totally fat-fingered a boilerplate file into the submissions. Tab-complete can be devilish.

We should have a really forgiving dialogue, this may be the first CLI thing a user does.

**Comment by kytrinyx** [comment]
> We should have a really forgiving dialogue, this may be the first CLI thing a user does.

Yeah, this sounds like a really great plan. Thanks so much for helping think this bit through!

**Comment by ErikSchierboom** [comment]
> Seems more a case a user would try to submit a file unintentionally

Agreed. I have seen several cases of (new) people submitting the tests file instead of the solution. If we can help prevent that, we should.

**Comment by ccare** [comment]
I just encountered the same issue while trying to submit a Haskell 'hello-world' solution. `nextercism submit` sent lots of stuff. Just for clarification, it looks like the 500 error is because one (or more) of those files has content that's too large for the data blob, probably because its binary. The specific issue appears to be it's uploading a binary in my `.stack-work/dist/` directory. Does this mean the regexes need to be tightened for this track. (tested on alpha.1 and alpha.3)

**Comment by kytrinyx** [comment]
> Does this mean the regexes need to be tightened for this track.

I think the right approach is to add a `cli_ignore_patterns` or some such which can be a list of ignore patterns that are specific to a track, in addition to any that are already defined by default or for test files or example files.

I'll think through this in the next few days and propose an approach.

**Comment by NobbZ** [comment]
@kytrinyx did you come up with a final solution for this now?

As it is now, there will be sent a lot of binary garbage along the actual submission (build-artifacts) as well as some boilerplate needed by the buildsystem (project definition, lock-file, etc) in the erlang track and probably others as well.

Especially for the erlang track, its annyoing, since the compiled artifacts are shown/listed before the actual submission, as well as some of the boilerplating stuff, just because their residental folders are first in the alphabet.

A first step to make me happy, were to provide a way to white- or blacklist folders, that way I could reduce the noise to a single file the erlang track. A students solution will always live in `src/`, while the tests will always be in `test/`.

Neither the basedir, nor the `includes/`-dir need to be considered when submitting, and especially not the `deps/` folder which is created only during compilation and holds the build artifacts as well as dependencies (and their artifacts).

I'd guess that Java and Rust are in a similar situation, but of course the folders they want to white-/blacklist might be a little bit different.

I'm not sure though how this will work out with other languages that tend to have flat-projects (or do not use a buildsystem at all).

**Comment by kytrinyx** [comment]
@NobbZ I'm focusing on the CLI for all of today (public holiday in this country!) and this near the top of my list.

I'll post a suggested solution here once I've had a chance to look through the discussion and think through some options.

**Comment by kytrinyx** [comment]
I've submitted an issue to the discussions repository that takes a broader look at the whole patterns thing (including the filtering problem discussed here): https://github.com/exercism/discussions/issues/192

**Comment by kytrinyx** [comment]
I've opened an issue in the CLI repo for the interactive confirmation when explicitly submitting files that would normally be filtered: https://github.com/exercism/cli/issues/480

**Comment by budmc29** [comment]
I don't thing this will be a common occurrence, but I installed by mistake jasmine for JavaScript locally instead of using globally and when using `nextercism submit` the node_modules folder was uploaded as well.
Should we be concerned with things like this?

**Comment by kytrinyx** [comment]
@budmc29 Yepp—this is exactly the kind of thing we want to avoid. `node_modules` is a good example of something we should filter, even if it's a rare occurrence.
