### ISSUE TITLE
Java Track:  Optional Exercise Listed as Milestone

### ISSUE THREAD

**Issue by BethanyG** [exercism/v2-feedback#61]
Completed the 'Two-Fer' exercise on the Java track.  Received a modal message window that showed 'Raindrops' was unlocked as an optional exercise.  When I returned to the main Java Track page, this is what I saw:

![screen shot 2017-08-22 at 11 01 11 am](https://user-images.githubusercontent.com/5923094/29580284-580666aa-872a-11e7-865a-444c8a83e7a0.png)
 
..so Raindrops is listed as a Main exercise - not an optional one.

**Comment by kytrinyx** [comment]
This looks like a bug somewhere in the backend. It's definitely listed as optional in the Java config:

https://github.com/exercism/java/blob/master/config.json#L95-L104

I don't know if it is in the importer or in the display logic, though. @iHiD would you put this one on your list to investigate?

**Comment by iHiD** [comment]
I suspect it's due to the fact [another exercises relies on it](https://github.com/exercism/java/blob/master/config.json#L199), which breaks the the contract, as side-exercises should only be unlocked by core, not other side exercises. 

@kytrinyx Configlet should check for this.
@ccare We should decide what to do with import in this situation.

**Comment by FridaTveit** [comment]
Sorry about that, we didn't know that side exercises should only be unlocked by core. I'll fix that as soon as possible. So the structure of the exercises isn't really a tree then, each core exercise just unlocks a bunch or other exercises?

If you find any more issues like this it would be great if you could tag the java maintainers here since we're the ones who have to fix it. I only found this issue by accident :)

**Comment by stkent** [comment]
This should now be fixed! 👏 @FridaTveit

**Comment by kytrinyx** [comment]
@FridaTveit Yepp—I wanted to work out if it was a bug on our end first and what we could do to make development easier before I pulled you all in. Thanks for fixing it.

>  So the structure of the exercises isn't really a tree then, each core exercise just unlocks a bunch or other exercises?

Yeah, that's a good point. I think we were talking about a tree at some point, and we decided to simplify it down, at least for now.

**Comment by iHiD** [comment]
Triaged to exercism/reboot#141

**Comment by stkent** [comment]
Link 404s?

**Comment by rpottsoh** [comment]
Reboot is private.
