### ISSUE TITLE
Readability difficulties

### ISSUE THREAD

**Issue by robphoenix** [exercism/v2-feedback#66]
The small size of the font used in the code for exercises and mentor comments, as well as the lightness of the mentor comments font, makes them hard to read. I find I have to move my face closer to the screen to read comfortably. I think this potentially reduces the usability and accessibility of the site

**Comment by NobbZ** [comment]
I'd add “and contrast to low” into the mix.

This is not only in mentors comments but on multiple places on the site. I've encountered the feeling the first time on a tracks overview page on most of the gray items.

I have to admit though, that I can read those very well at work where I have a calibrated monitor setup, while at home there is just a laptop without contrast controls, but brightness only… And of course not calibrated. I tried HDMI-TV screen and my old CRT monitor, the TV works fine after adjusting the contrast a bit, the CRT made many things worse, but hey, its a 20 year old CRT that has waited for moment about the last century ;)

**Comment by NobbZ** [comment]
The low contrast thing does also apply for the “highlighting” of links in the markdown editor:

![low-contrast-in-text-box-for-links](https://user-images.githubusercontent.com/58951/29610301-1ac068c4-87fa-11e7-801c-45023d685038.png)

I can't barely read the URL on my home-setup and I can check only tomorrow if it applies on my office setup as well or if calibrated environments make it better

**Comment by iHiD** [comment]
@robphoenix Mind adding a screenshot of where you mean?

By text in the mentor comment do you mean here: 
<img width="548" alt="screen shot 2017-08-23 at 13 22 45" src="https://user-images.githubusercontent.com/286476/29615538-3623b1b4-8806-11e7-84a0-67e604dfa634.png">

That's `14px #333` which is pretty standard, so either I'm guessing you mean something else, or that that's rendering weirdly somehow. A screenshot would be really appreciated.

@NobbZ If you could do the same for "mentors comments but on multiple places on the site.", that would be help me lots. I'll change the one you've screenshoted in the edit box above :)

**Comment by robphoenix** [comment]
<details>
![font-sizes](https://user-images.githubusercontent.com/9257284/29616222-b4450258-8808-11e7-9bfc-0300b85193f9.png)
</details>

I think for me, the font size in the code is too small (though the font is great), and the font in the comment is too thin/light and the letter-spacing is quite tight. It's uncomfortable to read.

If you compare it to the current site, the exercise takes up much more room on the screen, and the text is clearer and more legible.

<details>
![old-ex-exercise](https://user-images.githubusercontent.com/9257284/29616850-a9112ab8-880a-11e7-8386-58f4ae22ddf0.png)
</details>

For transparency I do have a slight visual impairment which may make the strain on my eyes more noticeable, but my complaint is not solely from the point of view of someone with a visual impairment, I think this is a general readability problem. And the only aspect of the new site that I feel is worse than the old. The exercise should be prominent, front and centre, and here it feels like it's almost playing second fiddle to the site design. Form over content and all that.

**Comment by iHiD** [comment]
> If you compare it to the current site, the exercise takes up much more room on the screen, and the text is clearer and more legible.

There's actually only 7px difference between the two (at least on my macbook). If that's not the case on yours then I need to understand which of the two sites is rendering differently for you. Could you check you have the same zoom level on both pages pls. More details appreciated :)

> I think for me, the font size in the code is too small (though the font is great), and the font in the comment is too thin/light and the letter-spacing is quite tight. It's uncomfortable to read.

Is this just in the code bit (both on the LHS and in the comment) or is this the actual text in the comment as well?

> For transparency I do have a slight visual impairment

Thanks for mentioning. I don't want the new site to be any harder than the old site for you though.

**Comment by robphoenix** [comment]
> There's actually only 7px difference between the two

Okay, it's not much, it's a shame the exercise takes up less screen real estate, but no biggie.

> > I think for me, the font size in the code is too small (though the font is great), and the font in the comment is too thin/light and the letter-spacing is quite tight. It's uncomfortable to read.

> Is this just in the code bit (both on the LHS and in the comment) or is this the actual text in the comment as well?

The LHS code: spacing is good, weight is good, font is too small
The RHS comment: It's the weight of the font, or lack of it, that is most problematic, (the spacing actually seems fine in comparison to the old site). These Github comments are 14px as well, so the size is ok, but these comments use a heavier font. If you change the font in v2 for the font used here, without changing the size or anything else, it immediately becomes more readable, if maybe less pretty.

<details>
![image](https://user-images.githubusercontent.com/9257284/29626509-d384fdd0-8826-11e7-8d51-99e7e04bf25c.png)
</details>

This is still the case if you use a grey rather than a black

<details>
![image](https://user-images.githubusercontent.com/9257284/29626726-9d972cb0-8827-11e7-8eb9-d5154221e175.png)
</details>

**Comment by NobbZ** [comment]
I do not think, that you will see on the screenshots what I see, since your setup is different from mine. As I already said, at work where I do have a calibrated setup everything is fine. The problem is mostly at my personal laptop(s) which have a fixed (and not very high) contrast. Therefore I'll provide some screenshots and try to explain what I do see there and what I do not see.

<details>

![track-view](https://user-images.githubusercontent.com/58951/29626415-ecee0944-882e-11e7-858e-180c5a7d1235.png)

</details>

1. The border/background of the progressbox is not visible at all unless I go really near to the monitor
2. Locked cards border is clearly visible, its content only blurry. Since I can read it at my office setup without problems I do assume the blurrynes is not intended.
3. The text in the “convepts” box is very small, and at least at my set up (work and home) its rasterized with "holes" or "superpixels" in that size, thats makes the text very blurry. When I zoom at least one level (110%) its rasterized fine.
4. The text “completed successfully” appears just as a blurry gray bar to me. The text line above has the same problem as described in 3.
5. (not in screenshot) The tracks quick status (“88 EXERCISES | 21 STUDENTS | 21 MENTORS”) has the same problem as described in 3.

<details>

![submission-view](https://user-images.githubusercontent.com/58951/29626417-f09fbcd6-882e-11e7-9f64-b1c72ad3060a.png)

</details>

1. Labels of inactive tabs have the similar problems as item 3 in the picture before, even though they seem to be slightly bigger.
2. Those controlls and the people-icon in the “community solutions” appear as gray uniform blurred shadows.
3. The slight mint-green background is barely distinguishable from the surrounding white background. It appears more like some blurryness surrounding the text. The text itself has the usual rasterization problems I described quite a few times now.

**Comment by robphoenix** [comment]
@iHiD I've been reading [this](http://thejameskyle.com/dear-javascript.html) and I want to make sure that this issue is not seen as a derogatory attack on exercism v2. I hope my language hasn't been overly antagonistic and I'd like to assure you and your team that the site is truly excellent, and we all appreciate the time, energy and hard work you're putting into it. I hope that this issue can be constructive and I assure you it comes from a belief in the project. :heart:

**Comment by iHiD** [comment]
@robphoenix Thank you for posting that. I definitely didn't find anything you said to be derogatory or antagonistic. It was clear you just want the best for the project :) Saying that, it does make a huge, huge impact when someone says they appreciate the work we've put in, so a very sincere thank you for that. We've been working on this a mixture of full-time and part-time for the last 8 months and put a lot of our hearts into it, so there's a lot of embedded emotion for us all :)

Thank you 💙

**Comment by iHiD** [comment]
>  it immediately becomes more readable, if maybe less pretty.

Yeah - this is the tradeoff that we need to get right. Fonts are incredibly annoying because browsers render them so differently (both to each other and to how the same font looks for example in a web-browser). We're going to spend a day working through the site looking at where/how we can increase contrast/size etc without spoiling the aesthetics. Thank you both for the examples - these will be really helpful to us.

**Comment by kytrinyx** [comment]
> Saying that, it does make a huge, huge impact when someone says they appreciate the work we've put in, so a very sincere thank you for that.

A thousand times this. Thank you @robphoenix 💖
