### ISSUE TITLE
Alumnus & gender specificity

### ISSUE THREAD

**Issue by robphoenix** [exercism/v2-feedback#81]
I noticed that `Alumnus` is spelt incorrectly: https://github.com/exercism/prototype/search?utf8=%E2%9C%93&q=allumnus&type=
In double checking my spelling I found out something I didn't know before; from [Wikipedia](https://en.wikipedia.org/wiki/Alumnus)

> alumnus (/əˈlʌmnəs/; masculine, plural alumni /əˈlʌmnaɪ/), an alumna (/əˈlʌmnə/; feminine, plural alumnae /əˈlʌmniː/), or an alumnum (/əˈlʌmnəm/; neuter, plural alumna /əˈlʌmnə/) 

that `alumnus` is a masculine term, with `alumnum` being gender neutral. In correcting the spelling on the site I wondered if it should be changed from `alumnus` to `alumnum`? 

I realise that `alumnus` is the commonly accepted term, in the same way that it's commonly accepted to call a group of mixed gender people `guys`, but language matters and small things like this can be a positive step towards improved inclusivity and diversity in our society. 

Downsides to doing this? People may assume we have misspelt `alumnus` on the site, it may lead to sizeable grunt work making the change across every aspect of Exercism (api, config.json's etc.). I'm willing to take on the grunt work of changing this across repos if needs be. 

Upsides? We stand up for gender equality. :balance_scale: 

If we don't decide to go down this route completely (concerns for breaking the backend, which is totally understandable) , then perhaps just for the public facing aspects of the site, if not that then this issue is just about fixing the spelling of `alumnus`.

**Comment by iHiD** [comment]
@robphoenix Thanks lots for raising this. It's important. And, if what you say is correct then I want to change it everywhere. However, I'm not convinced wikipedia is right.

Having checked dictionary.com, there is only one English word for this and that's [alumnus](http://www.dictionary.com/browse/alumnus). The definition mentions no gender specificity. Latin has the various spellings/genders that Wikipedia defines (as Latin does for most words) but I can't find many other sources for this being the case in English. Google does not recognise "alumnum" as a correctly spelt word.

So I'm going to take the controversial stand that Wikipedia is wrong. But I'm doing this with no knowledge other than 10mins of googling. Any thoughts on how we clarify this?

**Comment by NobbZ** [comment]
Google translate:

| latin | english |
|---|---|
| alumnus | alumnus, student, nursling, foster-son, foster-child |
| alumna | child, foster-child, alumna |
| alumnum | fosterling |

I'm neither an english nor a latin expert, but in general those words seem to be translated to roughly the same.

At my university there's a student who has already a degree in linguistics, perhaps I can reach for him and ask?

**Comment by tleen** [comment]
IIRC typically if of unspecified gender it would be alumnus in english. [alumnum](http://vicarius.thomasleen.com/alumnum) is a legit form of the word, its use is as a neuter adjective. Which if you think about it maps fairly well to a property in JSON.

It can always be shortened to 'alum', since this nicely side-steps the problem. Latinists may be upset, but its typical to shorten names in computer stuff anyway.

**Comment by ccare** [comment]
I always love a chance to put my institutional login to http://www.oed.com/ to good use.

I too, feel strongly that we should be inclusive, but there is no entry in the OED for alumnum. However there is for alumnus [1].

However, there probably is something in the Wikipedia account, because it does refer to a now-obsolete definition which relates to the masculine origins of the term. 

Obsolete defn: 
> A male pupil or student attending a particular school, university, or other seat of learning. Obs.

Since 1800, a second definition (originating in US English) records:

> A former pupil or student (typically male) of a particular school, university, etc.; a graduate of a particular seat of learning.

I suspect the 'typically male' bit stems more from poor gender equality in education rather than in it's etymology, but I'm not a linguist.

Finally, there is an extended colloquial definition, descibed as being 'in extended use'

> colloq. In extended use: a former member of any group; an ex-member of a team, band, organization, etc.
 
On this side of the Atlantic I'm not aware of any institutions using separate terms for gendered members of their alumni. If anything, it appears that the term has been de-gendered as a result of inclusion (similar to how the words authoress, poetess, or priestess are rarely seen in modern usage - see [2]).

Academically I find this stuff fascinating. But the key question for me would be whether non-male members of the Exercism alumni feel strongly about this.

[1] http://www.oed.com/view/Entry/5907 (for those with access)
[2] https://en.oxforddictionaries.com/writing-help/the-language-of-gender

**Comment by tleen** [comment]
> I too, feel strongly that we should be inclusive, but there is no entry in the OED for alumnum. However there is for alumnus [1].

I usually give benefit of the doubt to [Whitaker's Words](https://en.wikipedia.org/wiki/William_Whitaker%27s_Words). The word is real, it has [historic use](http://latin.packhum.org/search?q=alumnum), just not common and less so in the modern age.

**Comment by NobbZ** [comment]
> The word is real, it has historic use,

In latin scripts. Latin is dead. In german we say "Student" (m) and "Studentin" (f), but because of different forms in another language I do not ask you to change your side.

The roots of alumnus may be latin, but in my opinion, as I've read so far, it seems as if only alumnus has been carried over in a mostly gender neutral meaning into the english language, while alumna and alumnum have been left in the latin language.

You (the english people) also have borrowed "kaput" from german "kaputt". It got changed from our spelling. Roots are the same, meaning is the same, but it evolved differently. English and German are just different languages, as Latin and English are.

I'm not saying that using alumna or alumnum were false. I just try to say, that they might be without a meaning in modern English. Therefore what were the benefits of changing it, if no-one understands the word nor does even find them in an english dictionary?

**Comment by iHiD** [comment]
> alumnum is a legit form of the word

@tleen I'm not familiar with Whitaker's Words. It seems to be a Latin dictionary. You say "the word is  word is real, it has historic use" but is it a real *english* word with historic use in English or a real Latin word? I can't find any reference anywhere that it's ever been used in the English language.

If someone suggested we used abdominis instead of abdomen I would argue that they are wrong because first isn't an English word. That feels like the same case here.

**Comment by tleen** [comment]
Yep @NobbZ @iHiD I get your meaning. You are exactly right about it.

If we are concerned with the modern English usage of a latin term. `alumnum` wouldn't work. It is just not used where you see the English use of alum* in the modern age.

**Comment by iHiD** [comment]
My take on this is that we need to ask people who don't identify as male whether they're comfortable with being labelled with "alumnus". I think that's what really matters here.

I've [tweeted accordingly](https://twitter.com/iHiD/status/901063754925953026). RTs for reach appreciated.

**Comment by kytrinyx** [comment]
I do not want to speak for anyone other than myself. I feel completely comfortable going with general English usage here and referring to myself as an _alumnus_.

**Comment by iHiD** [comment]
Here are some replies to the tweet:
- "I prefer alum 👌"
- "Neither nor. I usually don't feel addressed by male descriptions. But to be frank, I don't have any idea for a different word. Sorry."
- "Women's colleges have "alumnae associations.""
- I guess if you want to be perfectly accurate, alumna? But more than one is alumni; that's gender neutral, I think. Apparently it's alumnae if the group is all female. Alumni for male or mixed. ... I knew alumna; if you read biographies of women it comes up. Alumnae I had to Google to find out.

I personally feel like I wouldn't understand anything other than alumni or alumnus, so if those words don't work, I suggest we choose a different word altogether, such as "Retired".

**Comment by kytrinyx** [comment]
> I suggest we choose a different word altogether, such as "Retired".

Let's do that. I like avoiding the whole issue where possible. I'm happy to submit PRs if we have consensus (consensa :trollface:) on this one.

**Comment by ccare** [comment]
I'm not so keen on 'retired', as it has age connotations, at least it would in the UK when pasted on a profile picture. It could easily look (at a glance) like we're attempting to describe people's professional status. It also suffers (as does Alumnus) with a degree of finality (e.g. you're not coming back, you've left, which makes it harder for people to just bow out for a while).

I know it's not as pretty, but maybe we should be just using something more like `inactive`, or alternatively, labelling the current ones as `active`. Or we could have two banks of profile pics, current maintainers, and past maintainers.

**Comment by NobbZ** [comment]
I really like the “alumnus” family of words, because it emphasizes exercisms character of a platform to learn and teach.

Since alumn* seems to be valid for any kind of former student (those who graduated and those that didn't pass the exams and had to leave therefore), I feel it as suitable for exercism.

The word “retired” is for me co-notated by a certain amount of wisdom and a certain grain of dementia, since I've learned this word primarily through “retirment home”. But maybe this co-notation isn't that strong for native speakers, but as @ccare pointed out this might as well differ between american and UK english.

But when thinking about it more, it feels as if “retirment” is a proper wording, while the alimnus family is not. Alumn* refers to students, while we list mentors and maintainers as one. But mentors and professors at my university do actually retire. They are refered to as “former professor/co-worker”.

**Comment by kytrinyx** [comment]
> I'm not so keen on 'retired', as it has age connotations, at least it would in the UK when pasted on a profile picture.

This is a really good point.

> maybe we should be just using something more like inactive

I feel like "inactive" sounds very passive, whereas "alumnus" is more of a celebration and recognition.

I'd suggest "emeritus", but it has the same problems as "alumnus".

**Comment by kytrinyx** [comment]
> The word “retired” is for me co-notated by a certain amount of wisdom and a certain grain of dementia

Ah. I really, really want to avoid the age-related connotations, since on Exercism students and maintainers and mentors could all be folks who are any age.

**Comment by tleen** [comment]
How about  "alum(s)" it's colloquial english but is completely neutral?

**Comment by iHiD** [comment]
My only concern with "alum" is that I'm just not sure I would have any idea what it meant if I saw it on a random site. It's appearing [here](v2.exercism.io/tracks/go) btw for context.

**Comment by kytrinyx** [comment]
We could totally honor "alumnus", "alumna", and "alumnum", btw. That's a very small concession and not a lot of complexity.

That way everyone can choose whether they want to identify as male or female or neither.

**Comment by kytrinyx** [comment]
Updated comment to account for non-binary folks.

**Comment by kytrinyx** [comment]
Since I'm not hearing any preferences one way or another, I'm leaning towards honoring all three forms and letting people choose the one they prefer (which we will then use in the ribbon on the site).

**Comment by robphoenix** [comment]
@kytrinyx this sounds like the most accommodating solution. Will there be a default if someone doesn't explicitly make a choice, or if they just happen to not get round to it for a while?

This turned into a fascinating dissection of language, thankyou everyone for the insights! :heart:

**Comment by kytrinyx** [comment]
> Will there be a default if someone doesn't explicitly make a choice, or if they just happen to not get round to it for a while?

I think probably not. If we know which pronouns people prefer(red) then maybe we go with that or our best guess? People are always welcome to correct it if they have a problem with it.

**Comment by robphoenix** [comment]
> I think probably not. If we know which pronouns people prefer(red) then maybe we go with that or our best guess? People are always welcome to correct it if they have a problem with it.

>  I feel completely comfortable going with general English usage here and referring to myself as an alumnus.

I think general, known usage, is the probably the best way forward, with the option to allow anyone who doesn't *feel addressed by male descriptions* to have the ability to change that. If we start off with everyone as an `alumnus` that puts the onus on those in that group to change that label as they see fit, rather than someone else having to make a *best guess*. Like language, it's not perfect, it would be great if we had a single catch all word, but I think at least enabling the choice for someone to choose the pronoun they feel represents them best is the next best situation.

Let me know if there's any work documenting this/updating the site that you'd like to offload onto me. I'm happy to put in the work to close this issue.

**Comment by kytrinyx** [comment]
> If we start off with everyone as an alumnus that puts the onus on those in that group to change that label as they see fit, rather than someone else having to make a best guess.

I think that is wise.

> Let me know if there's any work documenting this/updating the site that you'd like to offload onto me. I'm happy to put in the work to close this issue.

@robphoenix that would be fantastic. I updated the default `maintainer.json` file to link to this documentation:

https://github.com/exercism/docs/blob/master/maintaining-a-track/maintainer-configuration.md

I've opened an issue in our internal todo list for the prototype. If you would update the docs, then I think this can be closed.

**Comment by robphoenix** [comment]
Forgive me, I'm being dense, I'm not sure I understand what needs doing @kytrinyx.

> I updated the default maintainer.json file

I couldn't find this file. I assume the `maintainer.json` file is changing to accommodate this change? If so, how? I assume that is what would need documenting, if it is? Hopefully if you're able to point me in the direction of an updated `maintainer.json` file I should be able to work it out from there, :crossed_fingers: 

> I've opened an issue in our internal todo list for the prototype.

Would it help to open a PR on prototype for the spelling change? Or is this a moot point now?

**Comment by kytrinyx** [comment]
> Forgive me, I'm being dense

No, you're not. I haven't specified clearly enough.

> I updated the default maintainer.json file

> I couldn't find this file.

It's in the "request-new-language-track" repo which I use to bootstrap new tracks. https://github.com/exercism/request-new-language-track/blob/master/config/maintainers.json

>  I assume the maintainer.json file is changing to accommodate this change? If so, how? 

Yeah, good question.

I'd like to suggest that we keep the `alumnus` key, but let the value be null (still active) or a string representing the word you'd like to use to refer to your status ("alumnum", "alumnus", "alumna").

> Would it help to open a PR on prototype for the spelling change?

I think we've got this—there's been a lot going on and we have a whole backlog of little fixes. I think this is one of them.

So sorry I was unclear!

**Comment by iHiD** [comment]
Triaged to exercism/reboot#130
