### ISSUE TITLE
Transfered solutions do have no UUID

### ISSUE THREAD

**Issue by NobbZ** [exercism/v2-feedback#93]
Solutions transfered from the old exercism seem to do not have been converted to an UUID, but still have their hash instead.

**Comment by kytrinyx** [comment]
Yeah, we discussed this and decided to do two things:

- remove the hyphens from the solution uuid in v2 so that they look more like the old hash
- transfer the old hashes to v2 to make it easier to do redirects from old URLs to new.

Search engines use hyphens for meaningful word-boundaries, so removing the hyphens makes a wee bit more sense than keeping them.

**Comment by iHiD** [comment]
Fixed on master. Thanks.
